# Generated by Django 5.1 on 2024-08-19 22:12

import story_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=story_app.models.story_image_upload_path),
        ),
    ]
